name: Brennon
version: '2.0.0-SNAPSHOT'
main: com.envarcade.brennon.folia.BrennonFolia
api-version: '1.20'
folia-supported: true
description: Brennon Network Core System (Folia)
authors: [Envarcade]
load: STARTUP
